### ISSUE TITLE
TR2X bug: Lara changes foot when climbing steps

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#232] opened 2024-09-10 09:43 UTC
**Dev snapshot:** 0.2-432-gfc79d77

**Save:** [savegame.zip](https://github.com/user-attachments/files/16942796/savegame.zip) (This is in a room with 5 steps.)

_____________________

In OG, when starting from this position in the gym, Lara climbs both steps with her left foot first.

https://github.com/user-attachments/assets/169a42f9-bacb-4053-84fe-4629193c8b74

In TR2X, Lara climbs the 1st step with her right foot, then the 2nd step with her left foot. She will keep alternating if you try the save above.

https://github.com/user-attachments/assets/590a3177-0a91-4372-8e06-188ab1bf2bd0

**Comment by Richard-L** [comment] 2024-09-10 10:25
Wasn't something like this fixed in TR1X by @walkawayy ? May have been with taking steps backwards iirc.

It'd be nice to make this look more natural based on what foot is more likely to be used given her distance.

**Comment by aredfan** [comment] 2024-09-10 11:15
> Wasn't something like this fixed in TR1X by @walkawayy ? May have been with taking steps backwards iirc.

Yes walkawayy did fix the backward steps in tr1x, this is also covered under LostArtefacts/TRX#1602 for tr2x.

**Comment by rr-** [comment] 2024-09-10 22:04
Caused by 9d0c117a604a783fd51226ed644a31939f326c7f.

**Closed as completed** 2024-09-11 08:07 UTC
Labels: TRX bug, Priority: high, Unreleased, TR2
